DefaultLineageTable = [

    (       'Black',         'Unassigned', r'(None|Unassigned|)'),
    (  'WhiteSmoke', 'Other_Recombinants', r'X.*'),
    ('AntiqueWhite',                'XBF', r'XBF(\..*)?'),
    (    'DarkGray',          'Ancestral', r'(A)|(A\.2)|(A\.2\.[^5](\..*)?)|(A.[^2](\..*)?)|(A\.1[01234567](\..*)?)|(A\.[^1][0-9](\..*)?)|(B)|(B\.1\.1\.161)|(B\.1\.14)|(B\.1\.260)|(B\.1[0123589])|(B\.2[036789])|(B\.3(\.1)?)|(B.3[0-9])|(B\.4(\.[124567])?)|(B\.4[012345679])|(B\.5([01235678]?))|(B.6(\.[1234568])?)|(B\.6[01])'),
    (      'Yellow',        'D614G/Other', r'$OTHER'),
    (      'Orange',              'Alpha', r'((B\.1\.1\.7)|(Q))(\..*)?'),
    (   'Burlywood',               'Beta', r'B\.1\.351(\..*)?'),
    (   'FireBrick',              'Gamma', r'((B\.1\.1\.28)|(P))(\..*)?'),
    (    'DarkCyan',                 'Mu', r'((B\.1\.621)|(BB))(\..*)?'),
    (        'Cyan',            'Epsilon', r'B\.1\.42[97](\..*)?'),
    (   'LightBlue',               'Iota', r'B\.1\.526(\..*)?'),
    (  'BlueViolet',              'Delta', r'((B\.1\.617\.2)|(AY))(\..*)?'),
    (     'HotPink',               'BA.1', r'((BA\.1)|(B[CD]))(\..*)?'),
    (   'RoyalBlue',               'BA.2', r'((BA\.2)|(B[GHJLMNPRSY])|(C[ABHJMV])|(D[DSV])|(E[JP])|(F[JKRSV])|(G[PQ])|(JL))(\..*)?'),
    (         'Red',          'BA.2.12.1', r'((BA\.2\.12\.1)|(BG))(\..*)?'),
    (   'Chocolate',               'BA.4', r'((BA\.4)|(CS)|(DC))(\..*)?'),
    ('MidnightBlue',               'BA.5', r'((BA\.5)|(B[EFKQTUVWZ])|(C[CDEFGKLNPQRTUWYZ])|(D[ABEFGHJKLMNPQRTUWYZ])|(E[ABCDEFHNQRSTVWYZ])|(F[ABCFMNQ])|(JH))(\..*)?'),
    (        'Gold',               'BQ.1', r'((BQ\.1)|(C[WZ])|(D[KMNPRTU])|(E[ACDEFHNRSTVWYZ])|(F[ABCFMNQ])|(JH))(\..*)?'),
    ( 'ForestGreen',            'BA.2.75', r'((BA\.2\.75)|(B[LMNRY])|(C[ABHJV])|(D[SV])|(E[JP])|(F[JKRS])|(G[PQ])|(JL))(\..*)?'),
    (     'DarkRed',                'XBB', r'((XBB)|(E[GKLMU])|(F[DEGHLPTUWYZ])|(G[ABCDEFGHJKMNRSUVWYZ])|(H[ABCDEFGHJKLMNPQRSTUVYZ])|(J[ABCDEFGJK]))(\..*)?'),
    (      'Salmon',            'XBB.1.9', r'((XBB\.1\.9)|(EG)|(FL)|(GD)|(H[KNV])|(J[GJ]))(\..*)?'),
    (     'Crimson',            'XBB.1.5', r'((XBB\.1\.5)|(E[KLMU])|(F[DGHTZ])|(G[BCFGKNRUV])|(H[ACDJMPQRSTYZ])|(J[BDK]))(\..*)?'),
    ('LightSkyBlue',           'XBB.1.16', r'((XBB\.1\.16)|(FU)|(GY)|(HF)|(JF))(\..*)?'),
    (   'LimeGreen',               'CH.1', r'((CH\.1)|(DV)|(F[JKS])|(G[PQ])|(JL))(\..*)?'),
    (       'Khaki',               'BN.1', r'((BN\.1)|(DS)|(EJ)|(FR))(\..*)?'),
    (     'Thistle',                 'HK', r'HK(\..*)?'),
    (      'Purple',             'EG.5.1', r'((EG\.5\.1)|(H[KV])|(J[GJ]))(\..*)?'),
    (   'SlateBlue',           'FL.1.5.1', r'((FL\.1\.5\.1)|(HN))(\..*)?'),
    (       'Green',               'FE.1', r'((FE\.1)|(HE))(\..*)?'),
    (  'DarkOrange',             'FD.1.1', r'FD\.1\.1(\..*)?'),
    (    'Cornsilk',               'FK.1', r'((FK\.1)|(JL))(\..*)?'),
    (    'DarkBlue',         'XBB.1.16.6', r'((XBB\.1\.16\.6)|(JF))(\..*)?'),
    (  'Aquamarine',            'XBB.2.3', r'((XBB\.2\.3)|(G[EJMSZ])|(H[GH])|(J[AE]))(\..*)?'),
    (   'LightPink',                'XBC', r'((XBC)|(GT)|(HW))(\..*)?'),
    (     'Magenta',            'XBC.1.6', r'((XBC\.1\.6)|(GT)|(HW))(\..*)?'),
    (   'Goldenrod',               'GL.1', r'GL\.1(\..*)?'),
    (  'DodgerBlue',            'BA.2.86', r'BA\.2\.86(\..*)?'),

]
