DefaultLineageTable = [

    (       'Black',         'Unassigned', r'(None|Unassigned|)'),
    (  'WhiteSmoke', 'Other_Recombinants', r'X.*'),
    ('AntiqueWhite',                'XBF', r'XBF.*'),
    (    'Honeydew',                'XBC', r'XBC.*'),
    (    'DarkGray',          'Ancestral', r'(A)|(A\.2)|(A\.2\.[^5](\..*)?)|(A.[^2](\..*)?)|(A\.1[01234567](\..*)?)|(A\.[^1][0-9](\..*)?)|(B)|(B\.1\.1\.161)|(B\.1\.14)|(B\.1\.260)|(B\.1[0123589])|(B\.2[036789])|(B\.3(\.1)?)|(B.3[0-9])|(B\.4(\.[124567])?)|(B\.4[012345679])|(B\.5([01235678]?))|(B.6(\.[1234568])?)|(B\.6[01])'),
    (      'Yellow',        'D614G/Other', r'$OTHER'),
    (      'Orange',              'Alpha', r'(B\.1\.1\.7(\..*)?)|(Q\..*)'),
    (   'LightPink',               'Beta', r'B\.1\.351(\..*)?'),
    (   'FireBrick',              'Gamma', r'(B\.1\.1\.28)|(P\.1(\..*)?)'),
    (    'DarkCyan',                 'Mu', r'(B\.1\.621(\..*)?)|(BB.2)'),
    (        'Cyan',            'Epsilon', r'B\.1\.42[97](\..*)?'),
    (  'DodgerBlue',               'Iota', r'B\.1\.526'),
    (  'BlueViolet',              'Delta', r'(B\.1\.617\.2)|(AY\..*)'),
    (     'HotPink',            'BA.1/BD', r'(B.1.1.529)|(BA\.1(\..*)?)|(BD\..*)'),
    (     'Thistle',          'BA.1.1/BC', r'(BA\.1\.1(\..*)?)|(BC\..*)'),
    (   'RoyalBlue',               'BA.2', r'(BA\.2(\..*)?)|(B[HJPS]\..*)|(DD\..*)'),
    (        'Pink',       'BA.2.12.1/BG', r'(BA\.2\.12\.1(\..*)?)|(BG\..*)'),
    (   'LimeGreen',            'BA.4/CS', r'(BA\.4(\..*)?)|(CS\..*)'),
    (   'Chocolate',          'BA.4.6/DC', r'(BA\.4\.6(\..*)?)|(DC\..*)'),
    (  'DodgerBlue',               'BA.5', r'(BA\.5(\..*)?)|(B[EFKTUVWZ]\..*)|(C[CDEFGKLNQRTU]\..*)|(D[ABEFGHJQ]\..*)'),
    (   'LightBlue',          'BF.7-like', r'(BF\.(7|(11))(\..*)?)|(CP\..*)|(BA.5.2.(6|(13)|(3[45]))(\..*)?)|(BA\.5\.1\.((18)|(27))(\..*)?)|(BA\.5\.10\.1(\..*)?)|(BE\.1\.2(\..*)?)|(DW\..*)'),
    (        'Gold',               'BQ.1', r'BQ\.1(\..*)?'),
    (   'Goldenrod',             'BQ.1.1', r'(BQ\.1\.1(\..*)?)|(C[WZ](\..*)?)|(D[KMNPRTU](\..*)?)|(E[ADEFHRSTVWYZ](\..*)?)|(F[ACNM](\..*)?)'),
    (   'Burlywood',     'BQ.1.1.22-like', r'(BQ\.1\.1\.((22)|(13)|(20)|(24)|(10)|(21))(\..*)?)|(BQ\.1\.18(\..*)?)'),
    (        'Blue',       'BA.2.3.20/CM', r'(BA\.2\.3\.20(\..*)?)|(CM\..*)'),
    (    'Cornsilk',     'BA.5.2.18-like', r'(BA\.5\.2\.18(\..*)?)|(BF\.16(\..*)?)|(C[RQ]\..*)'),
    (    'DarkCyan',       'BA.2.75.2/CA', r'(BA\.2\.75\.2(\..*)?)|(CA\..*)'),
    ( 'ForestGreen',            'BA.2.75', r'(BA\.2\.75(\..*)?)|(B[LMNRY]\..*)|(C[BHV]\..*)|(D[SV]\..*)'),
    (     'DarkRed',                'XBB', r'XBB(\..*)?'),
    (        'Pink',            'XBB.1.9', r'(XBB\.1\.9(\..*)?)|(FL(\..*)?)|(EG(\..*)?)'),
    (     'Crimson',            'XBB.1.5', r'(XBB\.1\.5(\..*)?)|(EM)|(EK)|(EL)|(EU)|(FD)|(FG)|(FH)|(EU)'),
    ('LightSkyBlue',           'XBB.1.16', r'(XBB\.1\.16(\..*)?)|(FU.*)'),
    (   'LimeGreen',           'CH.1*/DV', r'(CH\.1(\..*)?)|(DV(\..*)?)'),
    (       'Khaki',               'BN.1', r'(BN\.1(\..*)?)|(DS(\..*)?)|(EJ(\..*)?)'),
    (      'Purple',               'EG.1', r'EG\.1(\..*)?'),
    (       'Green',               'FE.1', r'FE\.1(\..*)?'),
    (     'Magenta',             'FD.1.1', r'FD\.1\.1(\..*)?'),
    (    'DarkBlue',      'XBB.1.22.1/FY', r'(XBB\.1\.22\.1(\..*)?)|(FY.*)'),
    (  'Aquamarine',            'XBB.2.3', r'(XBB\.2\.3(\..*)?)|(EU.1(\..*)?)'),

]
