DefaultLineageTable = [

    (       'Black',         'Unassigned', r'(None|Unassigned|)'),
    (  'WhiteSmoke', 'Other_Recombinants', r'X.*'),
    ('AntiqueWhite',                'XBF', r'XBF.*'),
    (    'DarkGray',          'Ancestral', r'(A)|(A\.2)|(A\.2\.[^5](\..*)?)|(A.[^2](\..*)?)|(A\.1[01234567](\..*)?)|(A\.[^1][0-9](\..*)?)|(B)|(B\.1\.1\.161)|(B\.1\.14)|(B\.1\.260)|(B\.1[0123589])|(B\.2[036789])|(B\.3(\.1)?)|(B.3[0-9])|(B\.4(\.[124567])?)|(B\.4[012345679])|(B\.5([01235678]?))|(B.6(\.[1234568])?)|(B\.6[01])'),
    (      'Yellow',        'D614G/Other', r'$OTHER'),
    (      'Orange',              'Alpha', r'(B\.1\.1\.7(\..*)?)|(Q\..*)'),
    (   'LightPink',               'Beta', r'B\.1\.351(\..*)?'),
    (   'FireBrick',              'Gamma', r'(B\.1\.1\.28)|(P\.1(\..*)?)'),
    (    'DarkCyan',                 'Mu', r'(B\.1\.621(\..*)?)|(BB.2)'),
    (        'Cyan',            'Epsilon', r'B\.1\.42[97](\..*)?'),
    (  'DodgerBlue',               'Iota', r'B\.1\.526'),
    (  'BlueViolet',              'Delta', r'(B\.1\.617\.2)|(AY\..*)'),
    (     'HotPink',               'BA.1', r'((B.1.1.529)|(BA\.1)|(B[CD]))(\..*)?'),
    (   'RoyalBlue',               'BA.2', r'((BA\.2)|(B[HJPS])|(DD))(\..*)?'),
    (        'Pink',       'BA.2.12.1/BG', r'((BA\.2\.12\.1)|(BG))(\..*)?'),
    (   'Chocolate',            'BA.4/CS', r'((BA\.4)|(CS)|(DC))(\..*)?'),
    (  'DodgerBlue',               'BA.5', r'((BA\.5)|(B[EFKTUVWZ])|(C[CDEFGKLNPQRTUY])|(D[ABEFGHJLQWYZ])|(E[BQ]))(\..*)?'),
    (        'Gold',               'BQ.1', r'((BQ\.1)|(C[WZ])|(D[KMNPRTU])|(E[ACDEFHNRSTVWYZ])|(F[ABCFNMQ]))(\..*)?'),
    (        'Blue',          'BA.2.3.20', r'((BA\.2\.3\.20)|(CM)|(FV))(\..*)?'),
    ( 'ForestGreen',            'BA.2.75', r'((BA\.2\.75)|(B[LMNRY])|(C[ABHJV])|(D[SV])|(EP))(\..*)?'),
    (     'DarkRed',                'XBB', r'((XBB)|(GA)|(F[PW]))(\..*)?'),
    (        'Pink',            'XBB.1.9', r'((XBB\.1\.9)|(FL)|(EG)|(GD))(\..*)?'),
    (     'Crimson',            'XBB.1.5', r'((XBB\.1\.5)|(E[MKLU])|(F[DGHTZ])|(G[BC]))(\..*)?'),
    ('LightSkyBlue',           'XBB.1.16', r'((XBB\.1\.16)|(FU))(\..*)?'),
    (   'LimeGreen',               'CH.1', r'((CH\.1)|(DV)|(F[JS]))(\..*)?'),
    (       'Khaki',               'BN.1', r'((BN\.1)|(DS)|(EJ)|(FR))(\..*)?'),
    (      'Purple',               'EG.1', r'EG\.1(\..*)?'),
    (     'Thistle',               'EG.5', r'EG\.5(\..*)?'),
    (       'Green',               'FE.1', r'FE\.1(\..*)?'),
    (  'DarkOrange',             'FD.1.1', r'FD\.1\.1(\..*)?'),
    (    'Cornsilk',               'FK.1', r'FK\.1(\..*)?'),
    (    'DarkBlue',      'XBB.1.22.1/FY', r'((XBB\.1\.22\.1)|(FY))(\..*)?'),
    (  'Aquamarine',            'XBB.2.3', r'((XBB\.2\.3)|(EU.1)|(GE))(\..*)?'),
    (     'Magenta',            'XBC.1.6', r'XBC\.1\.6(\..*)?'),

]
